/**
 * Represents a security incident for investigation analysis.
 */
export interface Incident {
  /** Unique identifier for the incident. */
  id: string;
  /** Human-readable title of the incident. */
  title: string;
  /** Detailed description of the incident. */
  description: string;
  /** Severity level of the incident. */
  severity: 'low' | 'medium' | 'high' | 'critical';
  /** ISO-8601 timestamp when the incident was detected. */
  timestamp: string;
  /** Source system or chain (e.g., "stellar", "ethereum"). */
  source: string;
  /** Raw event data associated with the incident. */
  data?: Record<string, unknown>;
}

/**
 * Related event suggestion for investigation context.
 */
export interface RelatedEvent {
  /** Event identifier or reference. */
  id: string;
  /** Brief description of the related event. */
  description: string;
  /** Correlation score (0-1) indicating relevance. */
  correlationScore: number;
  /** ISO-8601 timestamp of the event. */
  timestamp: string;
  /** Event type or category. */
  eventType: string;
}

/**
 * Timeline entry for chronological incident analysis.
 */
export interface TimelineEntry {
  /** ISO-8601 timestamp of the event. */
  timestamp: string;
  /** Event description or summary. */
  description: string;
  /** Event type or action performed. */
  action: string;
  /** Actor or source that triggered the event. */
  actor?: string;
  /** Additional metadata or context. */
  metadata?: Record<string, unknown>;
}

/**
 * Complete investigation context generated by the AI assistant.
 */
export interface InvestigationContext {
  /** Incident being investigated. */
  incident: Incident;
  /** AI-generated contextual summary. */
  contextSummary: string;
  /** List of related events for investigation. */
  relatedEvents: RelatedEvent[];
  /** Chronological timeline of relevant activities. */
  timeline: TimelineEntry[];
  /** Key indicators of compromise identified. */
  indicators: string[];
  /** Suggested investigation steps. */
  investigationSteps: string[];
  /** Confidence score (0-1) of the analysis. */
  confidence: number;
}
